sudo: required
dist: trusty
language: node_js
node_js:
  - node


addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

before_install:
  - openssl aes-256-cbc -K $encrypted_b72a331dd17e_key -iv $encrypted_b72a331dd17e_iv -in deploy_rsa.enc -out deploy_rsa -d
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run ci

after_success:
  - npm run deploy:dev
