sudo: required
dist: xenial
language: node_js
node_js:
  - node

branches:
  only:
    - master

services:
  - xvfb

addons:
  ssh_known_hosts: drax.io
  chrome: stable

before_install:
  - openssl aes-256-cbc -K $encrypted_b72a331dd17e_key -iv $encrypted_b72a331dd17e_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - export DISPLAY=:99.0
  - phpenv global 7.1.27

script:
  - npm run ci

after_success:
  - npm run deploy:dev
