sudo: required
dist: trusty
language: node_js
node_js:
  - node


addons:
  ssh_known_hosts: drax.io
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

before_install:
  - openssl aes-256-cbc -K $encrypted_b72a331dd17e_key -iv $encrypted_b72a331dd17e_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run ci

after_success:
  - npm run deploy:dev
